### ISSUE TITLE
Codestar Fremework URL Validation Check

### ISSUE THREAD

**Issue by hmbashar** [Codestar/codestar-framework-old#615]
Add validate from themename/cs-framework/functions/validate.php

```
/**
 *
 * URL validate
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
if( ! function_exists( 'cs_validate_url' ) ) {
  function cs_validate_url( $value, $field ) {

    if (!empty($value)) {
        if ( ! filter_var($value, FILTER_VALIDATE_URL) ) {
            return esc_html__( 'Please write a valid url!', 'cs-framework' );
          }
    }


  }
  add_filter( 'cs_validate_url', 'cs_validate_url', 10, 2 );
}

```
Please add this filtering for URL

**Comment by Codestar** [comment]
Hi,

Oh nice idea, i will add this in v2. also you can check v2 from https://github.com/Codestar/codestar-framework

**Comment by hmbashar** [comment]
I requested the pool, but did not accept it. If you want, I can send the request again. Can I sent again? will you accept this request ?

**Comment by hmbashar** [comment]
> 
> 
> I requested the pool, but did not accept it. If you want, I can send the request again. Can I sent again? will you accept this request ?

**Comment by Codestar** [comment]
Hi @hmbashar 

No necessary to send again. because i noted this and going to add v2.... Actually i canceled all pull-requests because i released v2 here https://github.com/Codestar/codestar-framework that is why i canceled. Wait to next update coming.

**Comment by hmbashar** [comment]
I know, But If you want, I can sent you again to v2, Not old version.

**Comment by Codestar** [comment]
No no, i updated it already, only waiting to commit github repo. i am fixing somethings and i will send it today or tomorrow.

**Comment by Codestar** [comment]
Btw, thanks for coding :)
